In [1]:
import numpy as np


Since the closed-form solution to W involves V, and the closed-form solution to V involves W, we can use an Alternating Minimization scheme. For the least squares solutions, the algorithm is actually Alternating Least Squares (ALS). There are only three main steps of this iterative algorithm:



*   Initialize W and V with random values.
*   Iterative step 1: Update W by the least squares solution as mentioned above.
*   Iterative step 2: Update V by the least squares solution as mentioned above.



In [4]:
def rrvar(data, R, pred_step, maxiter = 100):
    """
    Reduced-rank VAR algorithm.
    R is the desired reduced rank.
    """
    
    N, T = data.shape
    X1 = data[:, : -1]
    X2 = data[:, 1 :]
    V = np.random.randn(R, N)
    for it in range(maxiter):
        W = X2 @ np.linalg.pinv(V @ X1)
        V = np.linalg.pinv(W) @ X2 @ np.linalg.pinv(X1)
    mat = np.append(data, np.zeros((N, pred_step)), axis = 1)
    for s in range(pred_step):
        mat[:, T + s] = W @ V @ mat[:, T + s - 1]
    return mat[:, - pred_step :]

Example Data: X is an array of observations

In [6]:
X = np.zeros((20, 10))
for i in range(20):
    X[i, :] = np.arange(i + 1, i + 11)

print(X)


[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [ 2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
 [ 3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
 [ 4.  5.  6.  7.  8.  9. 10. 11. 12. 13.]
 [ 5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]
 [ 6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]
 [ 7.  8.  9. 10. 11. 12. 13. 14. 15. 16.]
 [ 8.  9. 10. 11. 12. 13. 14. 15. 16. 17.]
 [ 9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
 [12. 13. 14. 15. 16. 17. 18. 19. 20. 21.]
 [13. 14. 15. 16. 17. 18. 19. 20. 21. 22.]
 [14. 15. 16. 17. 18. 19. 20. 21. 22. 23.]
 [15. 16. 17. 18. 19. 20. 21. 22. 23. 24.]
 [16. 17. 18. 19. 20. 21. 22. 23. 24. 25.]
 [17. 18. 19. 20. 21. 22. 23. 24. 25. 26.]
 [18. 19. 20. 21. 22. 23. 24. 25. 26. 27.]
 [19. 20. 21. 22. 23. 24. 25. 26. 27. 28.]
 [20. 21. 22. 23. 24. 25. 26. 27. 28. 29.]]


The goal is to use the defined rrvar function to forecast x11 and x12

In [8]:
pred_step = 2
R = 2
mat_hat = rrvar(X, R, pred_step)
print(mat_hat)

[[11. 12.]
 [12. 13.]
 [13. 14.]
 [14. 15.]
 [15. 16.]
 [16. 17.]
 [17. 18.]
 [18. 19.]
 [19. 20.]
 [20. 21.]
 [21. 22.]
 [22. 23.]
 [23. 24.]
 [24. 25.]
 [25. 26.]
 [26. 27.]
 [27. 28.]
 [28. 29.]
 [29. 30.]
 [30. 31.]]


As you can see, the results are the same as the ground truth data. 